// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSecond.Models;

#nullable disable

namespace WebApiSecond.Migrations
{
    [DbContext(typeof(VodaContext))]
    [Migration("20230620201351_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiSecond.Models.VodaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Count")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("VodaTypeModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VodaTypeModelId");

                    b.ToTable("Voda");
                });

            modelBuilder.Entity("WebApiSecond.Models.VodaTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("VodaType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("VodaTypeModel");
                });

            modelBuilder.Entity("WebApiSecond.Models.VodaModel", b =>
                {
                    b.HasOne("WebApiSecond.Models.VodaTypeModel", "TypeOfVoda")
                        .WithMany()
                        .HasForeignKey("VodaTypeModelId");

                    b.Navigation("TypeOfVoda");
                });
#pragma warning restore 612, 618
        }
    }
}
